config/routes.rb
Rails.application.routes.draw do
  resources :patients
  resources :reviewers
  
  root 'patients#home'
  get '/home' => 'patients#home'
  get '/analysis' => 'patients#index'
  get '/error' => 'patients#new'
  get '/patients/:job' => 'patients#show'
  post '/' => 'patients#create'
  get '/query_results' => 'patients#query_results'
  get '/scatter' => 'patients#scatter'
  post '/heatmap'=> 'patients#heatmap'
  get '/help' => 'patients#edit'
  get '/download/:job/:archivo1' => 'patients#download'
  get '/search' => 'patients#search'
  get '/enrichment/:job/:archivo1' => 'patients#enrichment'   

end

app/models/reviewer.rb
class Reviewer < ActiveRecord::Base
end

app/helpers/reviewers_helper.rb
module ReviewersHelper
end

app/views/reviewers/_form.html.erb
<%= form_for(@reviewer) do |f| %>
  <% if @reviewer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reviewer.errors.count, "error") %> prohibited this reviewer from being saved:</h2>

      <ul>
      <% @reviewer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviewers/edit.html.erb
<h1>Editing Reviewer</h1>

<%= render 'form' %>

<%= link_to 'Show', @reviewer %> |
<%= link_to 'Back', reviewers_path %>

app/views/reviewers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviewers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviewers.each do |reviewer| %>
      <tr>
        <td><%= reviewer.name %></td>
        <td><%= reviewer.last_name %></td>
        <td><%= link_to 'Show', reviewer %></td>
        <td><%= link_to 'Edit', edit_reviewer_path(reviewer) %></td>
        <td><%= link_to 'Destroy', reviewer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reviewer', new_reviewer_path %>

app/views/reviewers/new.html.erb
<h1>New Reviewer</h1>

<%= render 'form' %>

<%= link_to 'Back', reviewers_path %>

app/views/reviewers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reviewer.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @reviewer.last_name %>
</p>

<%= link_to 'Edit', edit_reviewer_path(@reviewer) %> |
<%= link_to 'Back', reviewers_path %>