config/routes.rb
Rails.application.routes.draw do
  resources :patients
  resources :reviewers
  
  root 'patients#home'
  get '/home' => 'patients#home'
  get '/analysis' => 'patients#index'
  get '/error' => 'patients#new'
  get '/patients/:job' => 'patients#show'
  post '/' => 'patients#create'
  get '/query_results' => 'patients#query_results'
  get '/scatter' => 'patients#scatter'
  post '/heatmap'=> 'patients#heatmap'
  get '/help' => 'patients#edit'
  get '/download/:job/:archivo1' => 'patients#download'
  get '/search' => 'patients#search'
  get '/enrichment/:job/:archivo1' => 'patients#enrichment'   

end

app/models/patient.rb
class Patient < ActiveRecord::Base
	validates :name, presence: true
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	before_action :set_patient, only: [:show, :edit, :update, :destroy]

	# GET /patients
	# GET /patients.json
	def find_job
	@url=params[:ide]
	if File.exist?("#{Rails.root}/public/#{@url}/index.html")
	@a||= Dir.glob("#{Rails.root}/public/#{@url}/gsea_report_for_na_pos_*.xls")
	@a1 =@a.to_s.delete('[]')
	@a2 =@a1.delete('""')
	@target||= File.read(@a2)
	@target1= CSV.parse(@target, :headers => true, :col_sep => "\t")
	redirect_to "/#{@url}"
	#@target= "results/#{@job}/gsea_report_for_na_pos*"
	##render :file => "/home/rmartin/preditest/results/fe30a8b3-b5ee-4afc-b336-33b64bbcc873/gsea_report_for_na_pos_1467200995861.html"
	else 
		redirect_to "/error"
	end
end

	def index
		@patients = Patient.all
	end

	# GET /patients/1
	# GET /patients/1.json
	def show
	require 'spreadsheet'	
	require 'csv'
	require 'nokogiri'

	@job=params[:id]
	@ide=params[:job]
	 
	system("mv #{Rails.root}/public/$(ls -t #{Rails.root}/public  | head -1) #{Rails.root}/public/#{@job}")
	
	if File.exist?("#{Rails.root}/public/#{@job}/index.html")
    @a||= Dir.glob("#{Rails.root}/public/#{@job}/gsea_report_for_na_pos_*.xls")
    @a1 =@a.to_s.delete('[]')
    @a2 =@a1.delete('""')
    @target||= File.read(@a2)
    @target1= CSV.parse(@target, :headers => true, :col_sep => "\t")

    @twofiles = Dir["#{Rails.root}/public/#{@job}/gsea_report_for_*.xls"]
    @twofiles_data = @twofiles.map {|tf| CSV.read(tf)}


    @csv_string = CSV.generate do |csv|
    csv << @target1.headers
    @twofiles_data.each do |data|
    data.shift
    data.each do |row|
    csv << row
end
end
end
#@data||= File.read(@csv_string)
@data2 = CSV.parse(@csv_string, :headers => true, :col_sep => "\t")

	##redirect_to "/#{@job}"
	#@target= "results/#{@job}/gsea_report_for_na_pos*"
	##render :file => "/home/rmartin/preditest/results/fe30a8b3-b5ee-4afc-b336-33b64bbcc873/gsea_report_for_na_pos_1467200995861.html"
	else 
		redirect_to "/error"
	end
		system("mv #{Rails.root}/testA.rnk #{Rails.root}/public/#{@job}")
		system("sed -i 's/-*//g' #{Rails.root}/public/#{@job}")

end

	# GET /patients/new
	def new
	end

	def heatmap
		job = params[:job]
		q = params[:symbol_name]
		q.upcase!
		genes = q.gsub(";", " ")
		genes1 = genes.inspect
		aver = "#{Rails.root}/public/#{@job}/gsea_report_for_*.xls"
		aver1 = aver.inspect
		print(aver1)
		system("/opt/python-3.6/bin/python3 heatmap.py #{genes1}")
		#archivo = Time.now
		render :heatmap
		#send_file "/home/rmartin/Downloads/heatmap1.pdf", filename: "heatmap-#{archivo}.pdf", type: 'application/pdf'
	end

	def query_results

		@@q = params[:symbol_name]
		@@q.upcase!
		if @@q.include? ";"
		genes=@@q.split(";")
		query = ""
		index = 0
		genes.each do |genes1|
			if index == 0
				query = "symbol = '#{genes1}'"
			else 
				query += "or symbol = '#{genes1}'"
				#like '%#{genes1}%'"
			end
			index += 1
		end
		@result = Nutrigenomic.where(query)
		else
		@result = Nutrigenomic.where("symbol = '#{@@q}'")
		end
def scatter
		genes = @@q.gsub(";", " ")
		genes.upcase!
		genes1 = genes.inspect
		system("/opt/python-3.6/bin/python3 plot2.py #{genes1}")
		#archivo = Time.now
		#render_to_string(:file => "basic-bar.html", :layout => nil).html_safe
		plotname = Dir.glob("./public/*").max_by {|f| File.mtime(f)}
		plotname.gsub!("./public","")
		#send_file "#{Rails.root}/#{plotname}", :type=> 'text/html',:disposition => 'attachment'
		redirect_to "#{plotname}"
	end

	end


	def home
	end

	def search
	end

	# GET /patients/1/edit
	def edit
	end

	# POST /patients
	# POST /patients.json
	def create
			require 'securerandom'
	 @job= SecureRandom.uuid
	ids_up= params[:ids_up]
	name=params[:name]
	organism=params[:organism]
	@list= ids_up.split('\n')
	File.open("testA.rnk", "w") do |file|
	@list.each do |v|	
	file.puts (v)


end
end

	 tar = File.open("testA.rnk").readlines.size





		require 'open3'
			if organism == "Homo_sapiens"
		  system("java -cp gsea2-2.2.2.jar -Xmx1024m xtools.gsea.GseaPreranked -gmx #{Rails.root}/NutriGeneset.gmt -collapse false -mode Max_probe -norm meandiv -nperm 1000 -rnk #{Rails.root}/testA.rnk -scoring_scheme weighted -rpt_label preditest_analysis -include_only_symbols true -make_sets true -plot_top_x 300 -rnd_seed 21101984 -set_max 3000 -set_min 1 -zip_report false -out #{Rails.root}/public") 
			
			else
			system("gseapy prerank -r test.rnk -g NutriGeneset.gmt -o results/#{@job} --min-size 0 --max-size 100000")
		 end
	
	

		 redirect_to "/patients/#{@job}"

	end

	def enrichment
		nombreArchivo  = params[:archivo1]
		job = params[:job]

		if File.exist?("#{Rails.root}/public/#{@job}/#{nombreArchivo}_genes.xls")
		system("#{Rails.root}/app/assets/enrichment.sh \"#{Rails.root}/public/#{job}/#{nombreArchivo}_genes.xls\" > temporal.txt")
		

		else
		require 'csv'
		  if File.exist?("#{Rails.root}/public/#{job}/#{nombreArchivo}.xls")   
	tar1= File.read("#{Rails.root}/public/#{job}/#{nombreArchivo}.xls")
        archivo=CSV.parse(tar1, :headers => true, :col_sep => "\t")
        archivo1=archivo["PROBE"]
  	    File.open("#{Rails.root}/public/#{job}/#{nombreArchivo}_genes.xls", "w") do |file1|
	    archivo1.each do |vt|	
	    file1.puts (vt)
	end
	end
		system("#{Rails.root}/app/assets/enrichment.sh \"#{Rails.root}/public/#{job}/#{nombreArchivo}_genes.xls\" > temporal.txt")
	
send_file "temporal.txt", filename: "#{nombreArchivo}_geneFunction.txt", type: "application/csv"
else
	flash[:success] = "There was an error processing the requested file, please try another query"
	redirect_to "/patients/#{job}"



end	
end
end
	def download
		require 'csv'

		 nombreArchivo  = params[:archivo1]
		 job = params[:job]

  if File.exist?("#{Rails.root}/public/#{job}/#{nombreArchivo}.xls")   

  tar1= File.read("#{Rails.root}/public/#{job}/#{nombreArchivo}.xls")

  archivo=CSV.parse(tar1, :headers => true, :col_sep => "\t")
  archivo1=archivo["PROBE"]
  	File.open("#{Rails.root}/public/#{job}/#{nombreArchivo}_genes.xls", "w") do |file1|
	archivo1.each do |vt|	
	file1.puts (vt)
end
end
puts("hello")
query_file = "#{Rails.root}/public/#{job}/#{nombreArchivo}_genes.xls"
matched_file = "#{Rails.root}/db_clean/#{nombreArchivo}.xls"
query_file1 = query_file.inspect
matched_file1 = matched_file.inspect

  nombreArchivo1 = nombreArchivo.inspect
	system("/opt/python-3.6/bin/python3 merge.py #{query_file1} #{matched_file1} #{job} > out 2>error ")
    system("mv #{Rails.root}/public/#{job}/results_merged.txt public/#{job}/#{nombreArchivo1}_matched.xls")
  
  		#render file: "prueba.xls", layout: false, content_type: "application/force-download"
		send_file "#{Rails.root}/public/#{job}/#{nombreArchivo}_matched.xls", filename: "#{nombreArchivo}_matched.xls", type: 'application/xls'


else
	flash[:success] = "There was an error processing the requested file, please try another query"
	redirect_to "/patients/#{job}"

end
end


	# PATCH/PUT /patients/1
	# PATCH/PUT /patients/1.json
	def update
		respond_to do |format|
			if @patient.update(patient_params)
				format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
				format.json { render :show, status: :ok, location: @patient }
			else
				format.html { render :edit }
				format.json { render json: @patient.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /patients/1
	# DELETE /patients/1.json
	def destroy
		@patient.destroy
		respond_to do |format|
			format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_patient
			require 'securerandom'
		id1= SecureRandom.uuid
			if File.exist?("results/#{@name}/gseapy_reports.csv")
		redirect_to "/#{id1}"
		end
end

		# Never trust parameters from the scary internet, only allow the white list through.
		def patient_params
			params.require(:patient).permit(:age, :gender, :weight, :city, :number_of)
		end

end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :number_of %><br>
    <%= f.text_field :number_of %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/_ie.html.erb
<div id="ie_warning">
  If you are using 
  <span class="ie">internet explorer</span>
  and this site seems 
  <span>very slow </span>
  you might
  need to try a different browser like
  <a href="http://www.mozilla.com">Firefox</a>
  ,
  <a href="http://www.apple.com/safari/">Safari</a>
  or
  <a href="http://www.google.com/chrome/">Google Chrome</a>
  <script>
    
    if (jQuery.browser.msie){
      $('#ie_warning').show();
    }

  </script>
</div>

app/views/patients/create.html.erb
<%= flash[:notice] %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Results:</strong>

</p>
<% require 'csv' %>
<% id1=params[:id1] %>
<% sleep(10) %>
<% target_text= File.read("results/#{@name}/gseapy_reports.csv") %>
<% target= CSV.parse(target_text, :headers => true) %>

<table>
  <thead>
	<tr>
	<th>Enriched terms</th>
	<th>ES</th>
	<th>NES</th>
	<th>PVAL</th>
	<th>FDR</th>
	<th>GENES</th>
	</tr>
  </thead>
  <tbody>
	<% target.each do |linea| %>
	<tr>
	<td><%= linea['Enrich_terms'] %></td>
	<td><%= linea['es'] %></td>
	<td><%= linea['nes'] %></td>
	<td><%= linea['pval'] %></td>
	<td><%= linea['fdr'] %></td>
	<td><%= linea['genes'] %></td>
	</tr>
	<% end %>
   </tbody>
</table>

app/views/patients/edit.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

<div class="container">


<br>
<br>

<b>Help for users to get started with NutrigeneDB and results interpretation</b>


<br>
<br>

<div id="accordion">
  <div class="card">
    <div class="card-header" id="headingTwo">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
	<h5> <b> Gene-centered analysis </b></h5>
        </button>
      </h5>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
      <div class="card-body">
        <p>
This module allows the exploration of differentially expressed genes accross nutrigenomics experiments. An exhaustive search of microarray gene expression assays on human cells in response to nutrients and bioactive food compounds was performed on GEO database. All the experiments included in NutriGenome DB are defined by a list of the top 10% differentially expressed genes, sorted by adjusted p-value. NutriGenome DB contains data generated among 32 different microarray platforms. As those platforms differ widely in characteristics such as the number of targets and available annotations, the number of genes defining each experiment may vary between 1500 and 3000.<br>
Users can look if a gene appears as differentially expressed among our collection of nutrigenomics experiments by introducing in the search box one or multiple human Gene Symbols. It is a exact match search, please pay attention to <b>spelling and capitalization. </b>Results are presented as a sortable table with log2 fold change values relative to the control, average expression levels, statistics and information about the target experiment, which is directly linked to the data source in GEO database.

<br>
<br>
<%= image_tag("help_search.png", :size => "1000x422", :style => "border: 2px solid black")%>
<p><u>Search results table:</u> The introduced genes are described by their expression level, statistical information and the source experiment. The experiment column contains the corresponding <b>GEO id</b> (link for further examination) as well as a brief summary; <b>human cell type, compound and treatment duration </b>. Each column is sortable, and the Search box on the top right allows for gene selection in case of a multiple gene search. Number of shown entries can also be tuned.</p>


</p>

      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingThree">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
	<h5> <b> Phenotype-centered analysis </b></h5> 
        </button>
      </h5>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
      <div class="card-body">
        This module allows users to find functional connections between their phenotype of interest and experiments included in NutriGenomeDB by comparing gene expression profiles. NutriGenomeDB (v.1.1) contains 231 gene expression profiles of human cells exposed to more than 140 different nutrients and bioactive food compounds. This analysis module is built upon the widely used pattern-matching algorithm Gene Set Enrichment Analysis (GSEA). The Nutrigenomic Gene Sets included in NutriGenomeDB are defined as the top 10% differentially expressed genes in the included nutrigenomics experiments (sorted by adjusted p-value). Therefore this tools allows users to find functional connections between a list of differentially expressed genes resulting from a phenotype of interest, with the Nutrigenomic Gene Sets defining different treatments with nutrients and bioactive food compounds available. <br>
<br>
<b>Required data input </b>: the Analysis tool expects as input a list of human Gene Symbols and their differential expression values (in log2 scale) separated by tabulator. This is the typical output from a gene differential expression experiment; from an Excel file, the corresponding Gene symbol and logFC columns should be copy-pasted directly into the application text box. Example data can be loaded by clicking at the bottom of the text box <b> (Load Example) </b>. The application automatically handles missing values (NA) and duplicated gene symbols in the data input. We recommend to perform queries with a minimum number of 500 genes and their fold change values in order to obtain meaningfull results.

<br>
<br>
<%= image_tag("analysis_tool.png", :size => "1000x422", :style => "border: 2px solid black")%>
<p><u>Analysis results table:</u> The resulting experiments are defined by their <b>GEO id</b> (link for further examination) as well as a brief description; <b>human cell type, compound and treatment information (compound concentration and duration) </b>. By clicking on "Details" link, users can download the list of overlapping genes between the query and matching experiments. Each column is sortable by Genes (number of overlapping genes), NES (Normalized Enrichment score; a high NES means that among the overlapping genes, a high portion of those are overexpressed in the query and the matching experiment, viceversa for a negative NES). The <b>Analysis</b> link allows users to perform a functional enrichment of overrepresented molecular functions among the overlapping genes. Search box on the top left allows users to browse for compounds or GEO id among the results.</p>

<br>
<br>
By clicking on the <b> Analysis </b> link, users are allowed to perform a functional enrichment analysis of the overlapping genes that connect the gene expression query and matched experiments from NutriGenomeDB. Via a java web-service, Panther database is interrogated for overrepresented molecular functions that characterize those overlapping genes. In this way users can get further insights into the functional connections highlighted by this analysis tool at molecular level.

<br>
<br>
<%= image_tag("enrichment.png", :size => "1000x422", :style => "border: 2px solid black")%>
<p><u>Functional enrichment results:</u> Results are grouped by genes belonging to the same GO Molecular Function. Information about statistics of the overrepresentation test are provided in the P-value and FDR columns.</p>

</p>


      </div>
    </div>
  </div>
<div id="accordion">
  <div class="card">
    <div class="card-header" id="headingFour">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
	<h5> <b> Submitting new data to NutriGenomeDB</b></h5>
        </button>
      </h5>
    </div>
    <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordion">
      <div class="card-body">
        <p>
The aim of NutriGenomeDB is to become a central hub of information related to nutrigenomics, by expanding its available gene expression data in order to create an useful and growing ressource for the cientific community. Therefore we encourage researchers to submit their data related to nutrigenomics experiments performed on human cell for inclusion in NutriGenomeDB. Please write us an <a href= "mailto: roberto.martin@imdea.org"> email</a> for further enquiries.

</p>

      </div>
    </div>
  </div>
</div>

<br>
<br>
<strong> Browser compatibility</strong>
<table border= "1">
<tbody>
<tr>
<td><strong>OS</strong></td>
<td><strong>Version</strong></td>
<td><strong>Chrome</strong></td>
<td><strong>Firefox</strong></td>
<td><strong>IE</strong></td>
<td><strong>Safari</strong></td>
</tr>
<tr>
<td>Linux</td>
<td>Ubuntu 16.04</td>
<td>not tested</td>
<td>49.0</td>
<td>n/a</td>
<td>n/a</td>
</tr>
<tr>
<td>Windows</td>
<td>10</td>
<td>71.0</td>
<td>57.0</td>
<td>11.0</td>
<td>n/a</td>
</tr>
<tr>
<td>MacOS</td>
<td>HighSierra</td>
<td>not tested</td>
<td>61.0</td>
<td>n/a</td>
<td>12.0</td>
</tr>
</tbody>
</table>

</div>

app/views/patients/find_job.html.erb
<%= flash[:notice] %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Results:</strong>

</p>
<% require 'csv' %>
<% id1=params[:id1] %>
<% sleep(10) %>
<% target_text= File.read("results/#{@name}/gseapy_reports.csv") %>
<% target= CSV.parse(target_text, :headers => true) %>

<table>
  <thead>
	<tr>
	<th>Enriched terms</th>
	<th>ES</th>
	<th>NES</th>
	<th>PVAL</th>
	<th>FDR</th>
	<th>GENES</th>
	</tr>
  </thead>
  <tbody>
	<% target.each do |linea| %>
	<tr>
	<td><%= linea['Enrich_terms'] %></td>
	<td><%= linea['es'] %></td>
	<td><%= linea['nes'] %></td>
	<td><%= linea['pval'] %></td>
	<td><%= linea['fdr'] %></td>
	<td><%= linea['genes'] %></td>
	</tr>
	<% end %>
   </tbody>
</table>

app/views/patients/heatmap.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/jqc-1.12.3/dt-1.10.16/datatables.min.js"></script>

<script src="https://d3js.org/d3.v3.min.js"></script>
<script src="https://underscorejs.org/underscore-min.js"></script>
<script src="clustergrammer.js" type="text/javascript"></script>

<script >
$().ready(function(){
d3.json("mult_view.json", function(response){
console.log("respuesta");
// args must contain root of container and the visualization JSON
var args = {
  root: '#heatmap',
  'network_data': response,
'matrix_update_callback':matrix_update_callback,
'cat_update_callback': cat_update_callback,
 'ini_view':{'N_row_var':20},
 'ini_expand':true
}

resize_container(args);

// Clustergrammer returns a Clustergrammer object in addition to making
// the visualization
var cgm = Clustergrammer(args);
check_setup_enrichr(cgm);
})
})

function matrix_update_callback(){console.log("respuesta2")}
function cat_update_callback(){console.log("respuesta3")}
function resize_container(args){

  var screen_width = window.innerWidth;
  var screen_height = window.innerHeight - 20;

  d3.select(args.root)
    .style('width', screen_width+'px')
    .style('height', screen_height+'px');
}

</script>

<body>
<div id="heatmap">  </div>

</body>

app/views/patients/new.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

<h1>There was an error</h1>

<h2>Something went wrong. please check the inout format of your data and try again</h2>

<%= link_to 'Back', patients_path %>